In [1]:
# !pip install nbformat

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# !pip install graphviz
# !pip install dtreeviz

In [4]:
import numpy as np
import pandas as pd
import warnings
pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore')
%matplotlib inline
import os
import gc

Đọc dataset df_remain

In [5]:
df_remain = pd.DataFrame(data=None)
for dirname, _, filenames in os.walk('../../Dataset/IDS 2018 Intrusion CSVs (CSE-CIC-IDS2018)/Remain/Re2/'):
    for filename in filenames:
        file_path = os.path.join(dirname, filename)
        print(file_path)
        df_temp = pd.read_csv(file_path)
        df_remain = pd.concat([df_remain, df_temp], ignore_index=True)
        del df_temp
        gc.collect()

../Dataset/IDS 2018 Intrusion CSVs (CSE-CIC-IDS2018)/Remain/Re2/02-22-2018.csv
../Dataset/IDS 2018 Intrusion CSVs (CSE-CIC-IDS2018)/Remain/Re2/02-23-2018.csv

In [6]:
df_remain.shape

(2097150, 80)

In [7]:
# check the number of rows and columns
print('Number of Rows (Samples): %s' % str((df_remain.shape[0])))
print('Number of Columns (Features): %s' % str((df_remain.shape[1])))

Number of Rows (Samples): 2097150
Number of Columns (Features): 80

In [8]:
df_remain.head()

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,22,6,22/02/2018 08:26:03,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,0,185.285714,363.396347,1.148228e+02,0.827114,1.284588e+06,4.865569e+06,19526080,12,20553406,2.283712e+06,6.467165e+06,19526080,22,782332,130388.666667,126280.381325,245143,2639,0,0,0,0,212,152,0.486537,0.340576,0,976,131.111111,281.994971,79521.163399,0,0,0,1,0,0,0,0,0,138.823529,106.3,185.285714,0,0,0,0,0,0,10,1063,7,1297,14600,222,4,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,Benign
1,34989,6,22/02/2018 08:26:24,790,2,0,848,0,848,0,424.0,599.626550,0,0,0.000000,0.000000,1.073418e+06,2531.645570,7.900000e+02,0.000000e+00,790,790,790,7.900000e+02,0.000000e+00,790,790,0,0.000000,0.000000,0,0,1,0,0,0,40,0,2531.645570,0.000000,0,848,565.333333,489.593028,239701.333333,0,1,0,0,1,0,0,0,0,848.000000,424.0,0.000000,0,0,0,0,0,0,2,848,0,0,234,-1,0,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,Benign
2,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396804e+07,75584115,4000203,99745913,2.493648e+07,3.396804e+07,75584115,4000203,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,Benign
3,500,17,22/02/2018 08:25:10,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396805e+07,75584130,4000189,99745913,2.493648e+07,3.396805e+07,75584130,4000189,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,Benign
4,500,17,22/02/2018 08:24:59,89481361,6,0,3000,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,3.352654e+01,0.067053,1.789627e+07,1.534519e+07,41990741,4000554,89481361,1.789627e+07,1.534519e+07,41990741,4000554,0,0.000000,0.000000,0,0,0,0,0,0,48,0,0.067053,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,583.333333,500.0,0.000000,0,0,0,0,0,0,6,3000,0,0,-1,-1,5,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,Benign

In [9]:
df_remain.columns

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [10]:
df_remain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2097150 entries, 0 to 2097149
Data columns (total 80 columns):
 #   Column             Dtype
---  ------             -----
 0   Dst Port           int64
 1   Protocol           int64
 2   Timestamp          object
 3   Flow Duration      int64
 4   Tot Fwd Pkts       int64
 5   Tot Bwd Pkts       int64
 6   TotLen Fwd Pkts    int64
 7   TotLen Bwd Pkts    int64
 8   Fwd Pkt Len Max    int64
 9   Fwd Pkt Len Min    int64
 10  Fwd Pkt Len Mean   float64
 11  Fwd Pkt Len Std    float64
 12  Bwd Pkt Len Max    int64
 13  Bwd Pkt Len Min    int64
 14  Bwd Pkt Len Mean   float64
 15  Bwd Pkt Len Std    float64
 16  Flow Byts/s        float64
 17  Flow Pkts/s        float64
 18  Flow IAT Mean      float64
 19  Flow IAT Std       float64
 20  Flow IAT Max       int64
 21  Flow IAT Min       int64
 22  Fwd IAT Tot        int64
 23  Fwd IAT Mean       float64
 24  Fwd IAT Std        float64
 25  Fwd IAT Max        int64
 26  Fwd IAT Min        int64
 27  Bwd IAT Tot        int64
 28  Bwd IAT Mean       float64
 29  Bwd IAT Std        float64
 30  Bwd IAT Max        int64
 31  Bwd IAT Min        int64
 32  Fwd PSH Flags      int64
 33  Bwd PSH Flags      int64
 34  Fwd URG Flags      int64
 35  Bwd URG Flags      int64
 36  Fwd Header Len     int64
 37  Bwd Header Len     int64
 38  Fwd Pkts/s         float64
 39  Bwd Pkts/s         float64
 40  Pkt Len Min        int64
 41  Pkt Len Max        int64
 42  Pkt Len Mean       float64
 43  Pkt Len Std        float64
 44  Pkt Len Var        float64
 45  FIN Flag Cnt       int64
 46  SYN Flag Cnt       int64
 47  RST Flag Cnt       int64
 48  PSH Flag Cnt       int64
 49  ACK Flag Cnt       int64
 50  URG Flag Cnt       int64
 51  CWE Flag Count     int64
 52  ECE Flag Cnt       int64
 53  Down/Up Ratio      int64
 54  Pkt Size Avg       float64
 55  Fwd Seg Size Avg   float64
 56  Bwd Seg Size Avg   float64
 57  Fwd Byts/b Avg     int64
 58  Fwd Pkts/b Avg     int64
 59  Fwd Blk Rate Avg   int64
 60  Bwd Byts/b Avg     int64
 61  Bwd Pkts/b Avg     int64
 62  Bwd Blk Rate Avg   int64
 63  Subflow Fwd Pkts   int64
 64  Subflow Fwd Byts   int64
 65  Subflow Bwd Pkts   int64
 66  Subflow Bwd Byts   int64
 67  Init Fwd Win Byts  int64
 68  Init Bwd Win Byts  int64
 69  Fwd Act Data Pkts  int64
 70  Fwd Seg Size Min   int64
 71  Active Mean        float64
 72  Active Std         float64
 73  Active Max         int64
 74  Active Min         int64
 75  Idle Mean          float64
 76  Idle Std           float64
 77  Idle Max           int64
 78  Idle Min           int64
 79  Label              object
dtypes: float64(24), int64(54), object(2)
memory usage: 1.2+ GB

In [11]:
# check the number of values for labels
df_remain['Label'].value_counts()

Label
Benign              2096222
Brute Force -Web        611
Brute Force -XSS        230
SQL Injection            87
Name: count, dtype: int64

In [12]:
df_remain.describe().style.background_gradient(cmap='Blues').set_properties(**{'font-family':'Segoe UI'})

Tiền xử lý dữ liệu

In [13]:
# Remove row with Label["Label"]
df_remain.drop(df_remain.loc[df_remain["Label"] == "Label"].index, inplace=True)

In [14]:
# Replace inf values to nan
df_remain = df_remain.replace([np.inf, -np.inf], np.nan)
# Count nan values
df_remain.isna().sum().sum()

22636

In [15]:
# Drop nan values
df_remain.dropna(inplace=True)
df_remain.isna().sum().sum()

0

In [16]:
df_remain.shape

(2085832, 80)

In [17]:
# Drop duplicate values
df_remain.drop_duplicates(inplace=True)
df_remain.shape

(2079952, 80)

In [18]:
df_remain['Label'] = df_remain['Label'].apply(lambda x: 0 if x.startswith("Benign") else 1)
df_remain['Label'].value_counts()

Label
0    2079024
1        928
Name: count, dtype: int64

In [19]:
# Remove timestamp columns
df_remain.drop(['Timestamp'], axis=1,inplace=True)

In [20]:
def convert_to_numeric(df):
  """Converts all features (except label) from object to float64 or int64.
  Args:
      df: A pandas DataFrame.

  Returns:
      A DataFrame with features converted to float64 (if possible).
  """
  # Select all columns except the label column (assuming 'Label' is the name)
  numeric_cols = df.columns.difference(['Dst Port', 'Protocol', 'Label'])
  # Try converting each column to float, ignoring errors for non-numeric values
  for col in numeric_cols:
    try:
      df[col] = pd.to_numeric(df[col], errors='coerce')
    except:
      pass
  return df

df_numeric = convert_to_numeric(df_remain.copy())
del df_remain
gc.collect()

106

In [21]:
# Replace inf values to nan
df_numeric = df_numeric.replace([np.inf, -np.inf], np.nan)
# Count nan values
print(df_numeric.isna().sum().sum())
df_numeric.dropna(inplace=True)

0

In [22]:
# Drop constant columns
# variances = df_numeric.var(numeric_only=True)
# constant_columns = variances[variances == 0].index
# df_numeric.drop(constant_columns, axis=1, inplace=True)

# print(constant_columns)
# print(df_numeric.shape)

In [23]:
print(df_numeric.shape)
print(df_numeric['Label'].value_counts())

(2079952, 79)
Label
0    2079024
1        928
Name: count, dtype: int64

In [24]:
# Process Protocol columns
df_numeric = df_numeric.astype({"Protocol": str})
df_numeric["Protocol"].unique()

array(['6', '17', '0'], dtype=object)

In [25]:
# Categorical data to onehot
df_numeric = pd.get_dummies(df_numeric, columns=['Protocol'])
df_numeric.head()

,Dst Port,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Protocol_0,Protocol_17,Protocol_6
0,22,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,0,185.285714,363.396347,1.148228e+02,0.827114,1.284588e+06,4.865569e+06,19526080,12,20553406,2.283712e+06,6.467165e+06,19526080,22,782332,130388.666667,126280.381325,245143,2639,0,0,0,0,212,152,0.486537,0.340576,0,976,131.111111,281.994971,79521.163399,0,0,0,1,0,0,0,0,0,138.823529,106.3,185.285714,0,0,0,0,0,0,10,1063,7,1297,14600,222,4,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,0,False,False,True
1,34989,790,2,0,848,0,848,0,424.0,599.626550,0,0,0.000000,0.000000,1.073418e+06,2531.645570,7.900000e+02,0.000000e+00,790,790,790,7.900000e+02,0.000000e+00,790,790,0,0.000000,0.000000,0,0,1,0,0,0,40,0,2531.645570,0.000000,0,848,565.333333,489.593028,239701.333333,0,1,0,0,1,0,0,0,0,848.000000,424.0,0.000000,0,0,0,0,0,0,2,848,0,0,234,-1,0,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,False,False,True
2,500,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396804e+07,75584115,4000203,99745913,2.493648e+07,3.396804e+07,75584115,4000203,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,False,True,False
3,500,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396805e+07,75584130,4000189,99745913,2.493648e+07,3.396805e+07,75584130,4000189,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,False,True,False
4,500,89481361,6,0,3000,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,3.352654e+01,0.067053,1.789627e+07,1.534519e+07,41990741,4000554,89481361,1.789627e+07,1.534519e+07,41990741,4000554,0,0.000000,0.000000,0,0,0,0,0,0,48,0,0.067053,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,583.333333,500.0,0.000000,0,0,0,0,0,0,6,3000,0,0,-1,-1,5,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,False,True,False

In [26]:
gc.collect()

0

In [27]:
# making Label column the last column again
df_numeric.insert(len(df_numeric.columns)-1, 'Label', df_numeric.pop('Label'))

In [28]:
df_numeric.head()

,Dst Port,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_0,Protocol_17,Protocol_6,Label
0,22,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,0,185.285714,363.396347,1.148228e+02,0.827114,1.284588e+06,4.865569e+06,19526080,12,20553406,2.283712e+06,6.467165e+06,19526080,22,782332,130388.666667,126280.381325,245143,2639,0,0,0,0,212,152,0.486537,0.340576,0,976,131.111111,281.994971,79521.163399,0,0,0,1,0,0,0,0,0,138.823529,106.3,185.285714,0,0,0,0,0,0,10,1063,7,1297,14600,222,4,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,False,False,True,0
1,34989,790,2,0,848,0,848,0,424.0,599.626550,0,0,0.000000,0.000000,1.073418e+06,2531.645570,7.900000e+02,0.000000e+00,790,790,790,7.900000e+02,0.000000e+00,790,790,0,0.000000,0.000000,0,0,1,0,0,0,40,0,2531.645570,0.000000,0,848,565.333333,489.593028,239701.333333,0,1,0,0,1,0,0,0,0,848.000000,424.0,0.000000,0,0,0,0,0,0,2,848,0,0,234,-1,0,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,False,False,True,0
2,500,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396804e+07,75584115,4000203,99745913,2.493648e+07,3.396804e+07,75584115,4000203,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,False,True,False,0
3,500,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396805e+07,75584130,4000189,99745913,2.493648e+07,3.396805e+07,75584130,4000189,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,False,True,False,0
4,500,89481361,6,0,3000,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,3.352654e+01,0.067053,1.789627e+07,1.534519e+07,41990741,4000554,89481361,1.789627e+07,1.534519e+07,41990741,4000554,0,0.000000,0.000000,0,0,0,0,0,0,48,0,0.067053,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,583.333333,500.0,0.000000,0,0,0,0,0,0,6,3000,0,0,-1,-1,5,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,False,True,False,0

In [29]:
df_numeric = df_numeric.astype({"Protocol_0": 'int64', "Protocol_17": 'int64', "Protocol_6": 'int64'})
df_numeric.head()

,Dst Port,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Protocol_0,Protocol_17,Protocol_6,Label
0,22,20553406,10,7,1063,1297,744,0,106.3,239.357496,976,0,185.285714,363.396347,1.148228e+02,0.827114,1.284588e+06,4.865569e+06,19526080,12,20553406,2.283712e+06,6.467165e+06,19526080,22,782332,130388.666667,126280.381325,245143,2639,0,0,0,0,212,152,0.486537,0.340576,0,976,131.111111,281.994971,79521.163399,0,0,0,1,0,0,0,0,0,138.823529,106.3,185.285714,0,0,0,0,0,0,10,1063,7,1297,14600,222,4,20,1027304.0,0.0,1027304,1027304,1.952608e+07,0.000000e+00,19526080,19526080,0,0,1,0
1,34989,790,2,0,848,0,848,0,424.0,599.626550,0,0,0.000000,0.000000,1.073418e+06,2531.645570,7.900000e+02,0.000000e+00,790,790,790,7.900000e+02,0.000000e+00,790,790,0,0.000000,0.000000,0,0,1,0,0,0,40,0,2531.645570,0.000000,0,848,565.333333,489.593028,239701.333333,0,1,0,0,1,0,0,0,0,848.000000,424.0,0.000000,0,0,0,0,0,0,2,848,0,0,234,-1,0,20,0.0,0.0,0,0,0.000000e+00,0.000000e+00,0,0,0,0,1,0
2,500,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396804e+07,75584115,4000203,99745913,2.493648e+07,3.396804e+07,75584115,4000203,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000203.0,0.0,4000203,4000203,3.191524e+07,3.792787e+07,75584115,7200679,0,1,0,0
3,500,99745913,5,0,2500,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,2.506368e+01,0.050127,2.493648e+07,3.396805e+07,75584130,4000189,99745913,2.493648e+07,3.396805e+07,75584130,4000189,0,0.000000,0.000000,0,0,0,0,0,0,40,0,0.050127,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,600.000000,500.0,0.000000,0,0,0,0,0,0,5,2500,0,0,-1,-1,4,8,4000189.0,0.0,4000189,4000189,3.191524e+07,3.792788e+07,75584130,7200693,0,1,0,0
4,500,89481361,6,0,3000,0,500,500,500.0,0.000000,0,0,0.000000,0.000000,3.352654e+01,0.067053,1.789627e+07,1.534519e+07,41990741,4000554,89481361,1.789627e+07,1.534519e+07,41990741,4000554,0,0.000000,0.000000,0,0,0,0,0,0,48,0,0.067053,0.000000,500,500,500.000000,0.000000,0.000000,0,0,0,0,0,0,0,0,0,583.333333,500.0,0.000000,0,0,0,0,0,0,6,3000,0,0,-1,-1,5,8,4000554.0,0.0,4000554,4000554,2.137020e+07,1.528109e+07,41990741,7200848,0,1,0,0

In [30]:
df_numeric = df_numeric.astype({"Dst Port": str})

In [31]:
df_numeric = df_numeric.astype({"Dst Port": 'int64'})
df_numeric.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2079952 entries, 0 to 2097149
Data columns (total 81 columns):
 #   Column             Dtype
---  ------             -----
 0   Dst Port           int64
 1   Flow Duration      int64
 2   Tot Fwd Pkts       int64
 3   Tot Bwd Pkts       int64
 4   TotLen Fwd Pkts    int64
 5   TotLen Bwd Pkts    int64
 6   Fwd Pkt Len Max    int64
 7   Fwd Pkt Len Min    int64
 8   Fwd Pkt Len Mean   float64
 9   Fwd Pkt Len Std    float64
 10  Bwd Pkt Len Max    int64
 11  Bwd Pkt Len Min    int64
 12  Bwd Pkt Len Mean   float64
 13  Bwd Pkt Len Std    float64
 14  Flow Byts/s        float64
 15  Flow Pkts/s        float64
 16  Flow IAT Mean      float64
 17  Flow IAT Std       float64
 18  Flow IAT Max       int64
 19  Flow IAT Min       int64
 20  Fwd IAT Tot        int64
 21  Fwd IAT Mean       float64
 22  Fwd IAT Std        float64
 23  Fwd IAT Max        int64
 24  Fwd IAT Min        int64
 25  Bwd IAT Tot        int64
 26  Bwd IAT Mean       float64
 27  Bwd IAT Std        float64
 28  Bwd IAT Max        int64
 29  Bwd IAT Min        int64
 30  Fwd PSH Flags      int64
 31  Bwd PSH Flags      int64
 32  Fwd URG Flags      int64
 33  Bwd URG Flags      int64
 34  Fwd Header Len     int64
 35  Bwd Header Len     int64
 36  Fwd Pkts/s         float64
 37  Bwd Pkts/s         float64
 38  Pkt Len Min        int64
 39  Pkt Len Max        int64
 40  Pkt Len Mean       float64
 41  Pkt Len Std        float64
 42  Pkt Len Var        float64
 43  FIN Flag Cnt       int64
 44  SYN Flag Cnt       int64
 45  RST Flag Cnt       int64
 46  PSH Flag Cnt       int64
 47  ACK Flag Cnt       int64
 48  URG Flag Cnt       int64
 49  CWE Flag Count     int64
 50  ECE Flag Cnt       int64
 51  Down/Up Ratio      int64
 52  Pkt Size Avg       float64
 53  Fwd Seg Size Avg   float64
 54  Bwd Seg Size Avg   float64
 55  Fwd Byts/b Avg     int64
 56  Fwd Pkts/b Avg     int64
 57  Fwd Blk Rate Avg   int64
 58  Bwd Byts/b Avg     int64
 59  Bwd Pkts/b Avg     int64
 60  Bwd Blk Rate Avg   int64
 61  Subflow Fwd Pkts   int64
 62  Subflow Fwd Byts   int64
 63  Subflow Bwd Pkts   int64
 64  Subflow Bwd Byts   int64
 65  Init Fwd Win Byts  int64
 66  Init Bwd Win Byts  int64
 67  Fwd Act Data Pkts  int64
 68  Fwd Seg Size Min   int64
 69  Active Mean        float64
 70  Active Std         float64
 71  Active Max         int64
 72  Active Min         int64
 73  Idle Mean          float64
 74  Idle Std           float64
 75  Idle Max           int64
 76  Idle Min           int64
 77  Protocol_0         int64
 78  Protocol_17        int64
 79  Protocol_6         int64
 80  Label              int64
dtypes: float64(24), int64(57)
memory usage: 1.3 GB

In [37]:
df_numeric.to_csv('../../Dataset/IDS 2018 Intrusion CSVs (CSE-CIC-IDS2018)/dataset_remain_2.csv', index=False)